service: serverless-dynamodb

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: local

plugins:
  - serverless-offline
  - serverless-dynamodb-local

custom:
  dynamodb:
    stages:
      - local
    start:
      migrate: true
      noStart: true
      seed: true
      port: 4566
    seed:
      heroes:
        sources:
          - table: Heroes
            sources: [ './seed/heroes.json' ]

package:
  individually: true 
  excludeDevDependencies: true

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: /hi

resources:
  Resources:
    Heroes:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Heroes
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1